// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_25N9hSNDEk7fjI9gIrKOVun4u5u_svg',
    appId: '1:730894837281:web:faae1d4f9b99ba2180e560',
    messagingSenderId: '730894837281',
    projectId: 'sanberappflutter-project',
    authDomain: 'sanberappflutter-project.firebaseapp.com',
    storageBucket: 'sanberappflutter-project.appspot.com',
    measurementId: 'G-EBCCTVLX2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHzk9iThQ3Lwopp4uOc7uO6UQzwyuBQ5Y',
    appId: '1:730894837281:android:a85ba92fe67580b480e560',
    messagingSenderId: '730894837281',
    projectId: 'sanberappflutter-project',
    storageBucket: 'sanberappflutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_zZRKNw9xBcsR_oPpZHTHzqX5CVi69M',
    appId: '1:730894837281:ios:b10e42ee89a02de980e560',
    messagingSenderId: '730894837281',
    projectId: 'sanberappflutter-project',
    storageBucket: 'sanberappflutter-project.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_zZRKNw9xBcsR_oPpZHTHzqX5CVi69M',
    appId: '1:730894837281:ios:b10e42ee89a02de980e560',
    messagingSenderId: '730894837281',
    projectId: 'sanberappflutter-project',
    storageBucket: 'sanberappflutter-project.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_25N9hSNDEk7fjI9gIrKOVun4u5u_svg',
    appId: '1:730894837281:web:7421723e327bf57f80e560',
    messagingSenderId: '730894837281',
    projectId: 'sanberappflutter-project',
    authDomain: 'sanberappflutter-project.firebaseapp.com',
    storageBucket: 'sanberappflutter-project.appspot.com',
    measurementId: 'G-G96YG4MD45',
  );

}